# Generated by Django 3.2.20 on 2023-09-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
